# Generated by .github/scripts/render-formula.sh in hernancerm/git-timeline.
# Edit that script, not this file: the release workflow overwrites it.
class GitTimeline < Formula
  desc "Git log wrapper improving readability"
  homepage "https://github.com/hernancerm/git-timeline"
  version "2.2.0"

  on_macos do
    # GraalVM 25 has no macOS Intel build, so neither do we. Without this an
    # Intel Mac would fail on a missing url instead of saying why.
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/hernancerm/git-timeline/releases/download/2.2.0/git-timeline-macos-arm64.tar.gz"
      sha256 "4f74fdc990a266ba0b365f6df7282bd8b2d26f0ace9cb0cb72aab837b8454716"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hernancerm/git-timeline/releases/download/2.2.0/git-timeline-linux-arm64.tar.gz"
      sha256 "9109d376cba1d76a12968080028bf73334a5fc77023c2092cfd9d1a05296994c"
    end

    on_intel do
      url "https://github.com/hernancerm/git-timeline/releases/download/2.2.0/git-timeline-linux-x86_64.tar.gz"
      sha256 "b6e4276c464dee5f55e4d345c38d48162b85fe2fce56264b4acc0ac4297673b6"
    end
  end

  def install
    bin.install "git-timeline"
    # Both are '#compdef -', so each only defines its own function. Whichever
    # _git the user has picks up the name it looks for; the other sits unused.
    zsh_completion.install "completions/_git_timeline", "completions/_git-timeline"
  end

  test do
    system "git-timeline", "--version"
  end
end
